### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by songhaohaohao** [meownoid/tensorfow-rbm#2]
Hello, I'm sorry to bother you, I use your code to run from the readme.py, there is an error after I change again,
  File "D:\360安全浏览器下载\tensorfow-rbm-master\tensorfow-rbm-master\rbm.py", line 29, in __init__
    from tqdm import tqdm_notebook as tq
      ImportError: No module named 'tqdm'
it's very kind of you if you can tell me the answer
Looking forward to your reply

**Comment by meownoid** [comment]
Sorry for sooo delayed reply: apparently I wasn't watching my own repository! Remove `tqdm='notebook'` option to avoid this issue or install `tqdm` python package.
