### ISSUE TITLE
I encontered a CUDA error when runing the code

### ISSUE THREAD

**Issue by yangyan00800** [meownoid/tensorfow-rbm#4]
I fit the RBM model with one batch...  (rbmobject1.partial_fit(batch_xs)) ..the code ran fine when i feed the model with first four batches, but there is an CUDA error when i feed the model with fifth batch.

there are commd information:

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_MISALIGNED_ADDRESS
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_MISALIGNED_ADDRESS
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1

how can i solve that?
I use the GBRBM model, and the training data are normalized before

**Comment by meownoid** [comment]
There is no any low level code in this project, just simple usage of the TensorFlow API. So, the problem is in your TensorFlow installation. The only thing I can recommend is to reinstall it or check any others tf models for the same error.
