### ISSUE TITLE
Question about "compute_visible_from_hidden"

### ISSUE THREAD

**Issue by luoping1004** [meownoid/tensorfow-rbm#6]
Thank you for your code. The structure is so clear which helped me a lot when I tried to write an RBM with tensorflow.

I have a simple question about the function "compute_visible_from_hidden". Could you tell me why sigmoid function was not used when computing visible based on hidden?

Thanks!

**Comment by meownoid** [comment]
It should be here, but there are the situations when you are interested in the output before the last activation. Task for which I used this implementation required this. I think I shouldn't confuse people, so I will add this activation.

**Comment by meownoid** [comment]
Done

**Comment by luoping1004** [comment]
Thanks!
